version: "3.8"

services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sykell
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build:
      context: ./backend
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      DB_USER: root
      DB_PASSWORD: root
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: sykell
      JWT_SECRET: your_jwt_secret
    volumes:
      - ./backend:/app/backend

  frontend:
    build:
      context: ./frontend
    depends_on:
      - backend
    ports:
      - "5173:5173"
    command: npm run dev -- --host
    environment:
      VITE_API_BASE_URL: http://localhost:8080
    volumes:
      - ./frontend:/app/frontend

volumes:
  db_data:
